services:
  solr1:
    # image: solr:9-slim
    build:
      context: '.'
      dockerfile: solr.Dockerfile
    container_name: solr1
    ports:
     - "8983:8983"
    volumes: 
    - $PWD/var/solr/data:/var/solr
    environment:
      - ZK_HOST=zoo1:2181
    depends_on:
      - zoo1
    tty: true
    stdin_open: true
    command: 'bash -e -c "solr zk cp /opt/solr-8.11.1/server/solr/security.json zk:security.json -z zoo1:2181;bin/solr start && tail -F /dev/null"'

  zoo1:
    tty: true
    image: zookeeper:3.6.2
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
